name: CI

on: [push, pull_request]

jobs:
  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_ps3" -type f -delete
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: GDRBDX-Xbox
          path: _build/Xbox

  build_ps3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_xbox" -type f -delete
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: GDRBDX-PS3
          path: _build/ps3
          
  build_xbox_vanilla_songs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_ps3" -type f -delete
          sed -i -e "s/;#define LOCK_DLC (1)/#define LOCK_DLC (1)/" _ark/config/macros.dta
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 5
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: GDRBDX-Xbox-vanilla-songs
          path: _build/Xbox

  build_ps3_vanilla_songs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ARK
        run: |
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          find . -name "*.*_xbox" -type f -delete
          sed -i -e "s/;#define LOCK_DLC (1)/#define LOCK_DLC (1)/" _ark/config/macros.dta
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 5
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: GDRBDX-PS3-vanilla-songs
          path: _build/ps3